### PR TITLE
wal-dir needs to be a directory in which the etcd user can write

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by treydock** [comment]
@ghoneycutt FYI that whatever value you put for `wal-dir`, Puppet will manage that resource so it doesn't need to be under `datadir`.

**Comment by treydock** [comment]
https://github.com/tailored-automation/puppet-module-etcd/blob/master/manifests/init.pp#L162-L171

**Comment by ghoneycutt** [comment]
I went with the example `/etcd-wal` and creating the directory as the etcd user failed. So changing the example so it works by default.

**Comment by treydock** [comment]
That shouldn't fail as the directory is created by user running puppet (root) and then chown to etcd user. Unless something stops new directories at root of filesystem.

**Pull request merged**
